### ISSUE TITLE
async dependency is missing

### ISSUE THREAD

**Issue by feugy** [Concorda/concorda-dashboard#185]
From a clean installation:

```
> git clone git@github.com:Concorda/concorda-dashboard.git
> cd concorda-dashboard
> npm i
> npm start

> concorda-dashboard@0.0.1 start D:\Workspaces\nearForm\fast\concorda-dashboard
> node ./server/start.js

module.js:341
    throw err;
    ^

Error: Cannot find module 'async'
    at Function.Module._resolveFilename (module.js:339:15)
    at Function.Module._load (module.js:290:25)
    at Module.require (module.js:367:17)
    at require (internal/module.js:16:19)
    at Object.<anonymous> (D:\Workspaces\nearForm\fast\concorda-dashboard\node_modules\gate-executor\gate-executor.js:10:14)
    at Module._compile (module.js:413:34)
    at Object.Module._extensions..js (module.js:422:10)
    at Module.load (module.js:357:32)
    at Function.Module._load (module.js:314:12)
    at Module.require (module.js:367:17)
```

Perhaps an optional/peer dependency from gate-executor.

**Comment by mirceaalexandru** [comment]
Async is part of concorda-dashboard dependency. Cannot reproduce on my system.

**Comment by feugy** [comment]
Was due to a specific [NPM bug](https://github.com/npm/npm/issues/9204) on Windows.
Fixed by upgrating to latest.
